### ISSUE TITLE
Unable to import bash.py

### ISSUE THREAD

**Issue by RatanShreshtha** [kennethreitz/bash.py#1]
I was trying to run some bash commands using the bash.py but I am getting `ModuleNotFoundError`. I followed following steps

- Created a directory named `bashing` and changed to it.
- Created a virtual environment using `pipenv --three` and then activated it using `pipenv shell`.
- Installed bash.py using `pipenv install bash.py` and in the repl when I imported bash I am getting following error.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'bash'
```
- But I am able to see bash.py in `pipenv graph`
```
bash.py==0.2.2
  - delegator.py [required: Any, installed: 0.1.1]
    - pexpect [required: >=4.1.0, installed: 4.7.0]
      - ptyprocess [required: >=0.5, installed: 0.6.0]
```

I am on mac osx 10.14.4 Mojave with python 3.7.3 and pipenv, version 2018.11.26.

**Comment by waketzheng** [comment]
I get the same error at ubuntu18, and manual fix it by run the following command at terminal (`pipenv shell` activated):
```
wget https://raw.githubusercontent.com/kennethreitz/bash.py/master/bash.py -P `python -c 'import delegator;from pathlib import Path;print(Path(delegator.__file__).parent)'`
```

**Comment by malfario** [comment]
This works for me on macOS 10.14.4, Python 3.7.3 and Pipenv 2018.11.26:

```
pipenv --three install bash.py
pipenv run python -c 'import bash; p=bash.run("echo hi!"); print(p.output)'
```

**Comment by kenneth-reitz** [comment]
this was an issue with a previous release
